// promiseFinally.js

Promise.resolve(" Useful result")
  .then(data => {
    console.log(data);
  })
  .finally(() => {
    console.log("๐งน Cleaned up");
  });

Promise.reject(" Something went wrong")
  .then(() => {
    console.log("โ Success"); // Skipped
  })
  .catch(err => {
    console.error("Caught:", err);
  })
  .finally(() => {
    console.log("๐งน Cleaned up");
  });

  